language: rust
rust:
    - nightly
    - 1.0.0-beta
notifications:
    email:
        - mitchell.nordine@gmail.com
os:
    - linux
    - osx
env:
    - LD_LIBRARY_PATH: /usr/local/lib
install:
    - curl -O http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
    - tar xfz pa_stable_v19_20140130.tgz
    - (cd portaudio/ && ./configure && make && sudo make install)
before_script:
    - rustc --version
    - cargo --version
script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo doc --verbose
